# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Custom
                                 A QGIS plugin
 Load some layers...
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-14
        copyright            : (C) 2020 by Andres Calderon
        email                : acald013@ucr.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Custom class from file Custom.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Loader import Custom
    return Custom(iface)
