#!/bin/bash

for n in $(seq 1 $1)
do
    for C in 1 2 5 10 25 50 100 200 500 1000
    do
	echo "Runing $n ./sdcel CA/${C}/ /home/acald013/RIDIR/local_path/CA/${C}/ 1e3"
	./sdcel CA/${C}/ /home/acald013/RIDIR/local_path/CA/${C}/ 1e3
    done
done
