#!/usr/bin/bash
                                                                                                                                                     
./Perf -d CA_scaleup/S0 -t 1e-3 -p 1000 -x 3  -m yarn -n 5
./Perf -d CA_scaleup/S1 -t 1e-3 -p 1000 -x 6  -m yarn -n 5
./Perf -d CA_scaleup/S2 -t 1e-3 -p 1000 -x 9  -m yarn -n 5
./Perf -d CA_scaleup/S3 -t 1e-3 -p 1000 -x 12 -m yarn -n 5