#!/bin/bash

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
    case $1 in
	-d|--dataset)
	    DATASET="$2"
	    shift
	    shift
	    ;;
	-t|--tolerance)
	    TOLERANCE="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-l|--level)
	    LEVEL="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-m|--master)
	    MASTER="$2"
	    shift # past argument
	    shift # past value
	    ;;	
	--debug)
	    DEBUG="--debug"
	    shift # past argument
	    ;;
	-*|--*)
	    echo "Unknown option $1"
	    exit 1
	    ;;
	*)
	    POSITIONAL_ARGS+=("$1") # save positional arg
	    shift # past argument
	    ;;
    esac
done
set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

echo "DATASET    = ${DATASET}"
echo "TOLERANCE  = ${TOLERANCE}"
echo "LEVEL      = ${LEVEL}"
if [ -v DEBUG ]; then echo "DEBUG      = YES";  else DEBUG=""; fi
if [ -v MASTER ]
then
    echo "MASTER     = ${MASTER}"
else
    MASTER="yarn"
    echo "MASTER     = yarn"
fi

EXECUTORS=12
CORES=9
DMEMORY=35g
EMEMORY=20g
SPARK_JARS=$HOME/Spark/2.4/jars/
JAR=$HOME/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar
CLASS="edu.ucr.dblab.sdcel.CellAgg"
LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties

spark-submit \
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars ${SPARK_JARS}geospark-1.2.0.jar,${SPARK_JARS}scallop_2.11-3.1.5.jar \
    --master $MASTER --deploy-mode client \
    --num-executors $EXECUTORS --executor-cores $CORES \
    --executor-memory $EMEMORY --driver-memory $DMEMORY \
    --class $CLASS $JAR \
    --input $DATASET --tolerance $TOLERANCE --level $LEVEL
