#!/bin/bash

ES=(650 950 1250 1550 1850 2150 2500 2800 3150 3450 3800 4100 4350 4650)
LS=(2 3 4 5 6 7 8 9 10 11 12 13 14 15)

for i in "${!ES[@]}";do
    echo "./sdcel_partitioner_bycapacity gadm/raw/level0 gadm/raw/level1 Test/EPP/E${LS[i]}K/ /home/acald013/RIDIR/local_path/EPP/E${LS[i]}K/ ${ES[i]} 1e-8"
    ./sdcel_partitioner_bycapacity gadm/raw/level0 gadm/raw/level1 Test/EPP/E${LS[i]}K/ /home/acald013/RIDIR/local_path/EPP/E${LS[i]}K/ ${ES[i]} 1e-8
done

