#!/bin/bash

ES=(2 3 4 5 6 7 8 9 10 11 12 13 14 15)
#ES=(15)
for n in $(seq 1 $1)
do
    for E in "${ES[@]}"
    do
	echo "Run $n ./sdcel_notmerge Test/EPP/E${E}K /home/acald013/RIDIR/local_path/E${E}K 1e-8"
	./sdcel_notmerge Test/EPP/E${E}K /home/acald013/RIDIR/local_path/EPP/E${E}K 1e-8 "E${E}K" "2s"
    done
done
