#!/usr/bin/env bash

## Comparing US2000 full layer vs US2010 small layer...

## Run just one time
# hdfs dfs -mkdir Census/MainUS/compare
# hdfs dfs -mkdir Census/MainUS/compare/T0
# hdfs dfs -mkdir Census/MainUS/compare/T1

##
TAG=1
PARTITIONS=7000

##
hdfs dfs -cp Census/MainUS/scaleup/S3/A3.wkt Census/MainUS/compare/T${TAG}/A.wkt
hdfs dfs -cp Census/MainUS/scaleup/S0/B0.wkt Census/MainUS/compare/T${TAG}/B.wkt

##
hdfs dfs -mkdir Census/MainUS/compare/T${TAG}/P${PARTITIONS}

##
mkdir -p ~/RIDIR/local_path/Census/MainUS/compare/T${TAG}/P${PARTITIONS}
cp ~/RIDIR/local_path/Census/MainUS/P${PARTITIONS}/* ~/RIDIR/local_path/Census/MainUS/compare/T${TAG}/P${PARTITIONS}/

##
TOLERANCE=1e-3
HDFS_PATH=Census/MainUS/compare/T${TAG}
LOCAL_PATH=${HOME}/RIDIR/local_path/${HDFS_PATH}
PARAMS=(
    ${HDFS_PATH}/A.wkt ${HDFS_PATH}/B.wkt \
		${HDFS_PATH}/P${PARTITIONS} \
		${LOCAL_PATH}/P${PARTITIONS}/quadtree.wkt ${LOCAL_PATH}/P${PARTITIONS}/boundary.wkt \
		${TOLERANCE}
)
PARTITIONER_PATH=${HOME}/RIDIR/Code/SDCEL/sdcel_partitioner_byquadtree
echo "${PARTITIONER_PATH} ${PARAMS[@]}"
$PARTITIONER_PATH ${PARAMS[@]}

## OUTPUT
# 2022-04-28 11:40:02,929|35247|application_1648870353198_1284|INFO|edgesA=35417146
# 2022-04-28 11:40:10,709|43027|application_1648870353198_1284|INFO|edgesB=9173258

##
${HOME}/RIDIR/Code/SDCEL/Perf -d $HDFS_PATH -t $TOLERANCE -p $PARTITIONS -m yarn -n 5
