#!/usr/bin/bash

PARTS=4
ITERATIONS=5
TOLERANCE=1e-3
PARTITIONS=7000
HDFS_PATH=Census/MainUS/scaleup
PARTS_PATH=${HOME}/Datasets/Census/MainUS/scaleup

##
echo "Checking ROOT folder..."
hdfs dfs -test -d ${HDFS_PATH}
if [ $? == 0  ]; then
    hdfs dfs -rm -r -skipTrash ${HDFS_PATH}
fi
hdfs dfs -mkdir ${HDFS_PATH}
##
hdfs dfs -mkdir ${HDFS_PATH}/S0
hdfs dfs -mkdir ${HDFS_PATH}/S1
hdfs dfs -mkdir ${HDFS_PATH}/S2
hdfs dfs -mkdir ${HDFS_PATH}/S3
##
hdfs dfs -mkdir ${HDFS_PATH}/S0/P${PARTITIONS}
hdfs dfs -mkdir ${HDFS_PATH}/S1/P${PARTITIONS}
hdfs dfs -mkdir ${HDFS_PATH}/S2/P${PARTITIONS}
hdfs dfs -mkdir ${HDFS_PATH}/S3/P${PARTITIONS}

##
echo "Uploading  datasets..."
hdfs dfs -put ${PARTS_PATH}/A0.wkt ${HDFS_PATH}/S0
hdfs dfs -put ${PARTS_PATH}/B0.wkt ${HDFS_PATH}/S0
hdfs dfs -put ${PARTS_PATH}/A1.wkt ${HDFS_PATH}/S1
hdfs dfs -put ${PARTS_PATH}/B1.wkt ${HDFS_PATH}/S1
hdfs dfs -put ${PARTS_PATH}/A2.wkt ${HDFS_PATH}/S2
hdfs dfs -put ${PARTS_PATH}/B2.wkt ${HDFS_PATH}/S2
hdfs dfs -put ${PARTS_PATH}/A3.wkt ${HDFS_PATH}/S3
hdfs dfs -put ${PARTS_PATH}/B3.wkt ${HDFS_PATH}/S3

##
echo "Copying quadtree and boundary data..."
mkdir -p ${HOME}/RIDIR/local_path/${HDFS_PATH}/S0/P${PARTITIONS}
mkdir -p ${HOME}/RIDIR/local_path/${HDFS_PATH}/S1/P${PARTITIONS}
mkdir -p ${HOME}/RIDIR/local_path/${HDFS_PATH}/S2/P${PARTITIONS}
mkdir -p ${HOME}/RIDIR/local_path/${HDFS_PATH}/S3/P${PARTITIONS}
##
cp ${HOME}/RIDIR/local_path/Census/MainUS/P${PARTITIONS}/* ${HOME}/RIDIR/local_path/${HDFS_PATH}/S0/P${PARTITIONS}
cp ${HOME}/RIDIR/local_path/Census/MainUS/P${PARTITIONS}/* ${HOME}/RIDIR/local_path/${HDFS_PATH}/S1/P${PARTITIONS}
cp ${HOME}/RIDIR/local_path/Census/MainUS/P${PARTITIONS}/* ${HOME}/RIDIR/local_path/${HDFS_PATH}/S2/P${PARTITIONS}
cp ${HOME}/RIDIR/local_path/Census/MainUS/P${PARTITIONS}/* ${HOME}/RIDIR/local_path/${HDFS_PATH}/S3/P${PARTITIONS}

##
for((PART=0; PART<$PARTS; PART++)); do
    PART_PATH=${HDFS_PATH}/S${PART}
    LOCAL_PATH=${HOME}/RIDIR/local_path/$PART_PATH
    PARAMS=(
	${PART_PATH}/A${PART}.wkt ${PART_PATH}/B${PART}.wkt\
	${PART_PATH}/P${PARTITIONS}\
	${LOCAL_PATH}/P${PARTITIONS}/quadtree.wkt ${LOCAL_PATH}/P${PARTITIONS}/boundary.wkt\
	${TOLERANCE}
    )
    echo "./sdcel_partitioner_byquadtree ${PARAMS[@]}"
    ./sdcel_partitioner_byquadtree ${PARAMS[@]}
done

##
#./Perf -d ${HDFS_PATH}/S0 -t ${TOLERANCE} -p ${PARTITIONS} -x 3  -m yarn -n ${ITERATIONS}
#./Perf -d ${HDFS_PATH}/S1 -t ${TOLERANCE} -p ${PARTITIONS} -x 6  -m yarn -n ${ITERATIONS}
#./Perf -d ${HDFS_PATH}/S2 -t ${TOLERANCE} -p ${PARTITIONS} -x 9  -m yarn -n ${ITERATIONS}
#./Perf -d ${HDFS_PATH}/S3 -t ${TOLERANCE} -p ${PARTITIONS} -x 12 -m yarn -n ${ITERATIONS}
