#!/bin/bash

HPATH="Test/EPP/"
LPATH="/home/acald013/RIDIR/local_path/EPP/"
LS=(2 3 4 5 6 7 8 9 10 11 12 13 14 15)

for L in "${LS[@]}"
do
    echo "rm -fR ${LPATH}E${L}K/"
    mkdir ${LPATH}E${L}K/
    echo "hdfs dfs -rm -f -r ${HPATH}E${L}K/"
    hdfs dfs -mkdir ${HPATH}E${L}K/
done
