#!/bin/bash

PS=(1000 2000 3000 4000 5000 6000 7000 8000 10000 11000 12000 13000 14000 15000 16000 17000 18000 19000 20000)
#PS=(5000)
HDFS_PATH=$1
TOLERANCE=$2
N=$3

for n in $(seq 1 $N)
do
    for P in "${PS[@]}"
    do
	echo "Run $n ./sdcel2_debug $HDFS_PATH/P$P /home/acald013/RIDIR/local_path/$HDFS_PATH/P$P/ $TOLERANCE \"${P}_${HDFS_PATH}_${TOLERANCE}_${n}\""
	./sdcel2_debug $HDFS_PATH/P$P /home/acald013/RIDIR/local_path/$HDFS_PATH/P$P/ $TOLERANCE "${P}_${HDFS_PATH}_${TOLERANCE}_${n}"
    done
done
