#!/bin/bash

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
	-d|--dataset)
	    DATASET="$2"
	    shift
	    shift
	    ;;
	-t|--tolerance)
	    TOLERANCE="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-f|--first)
	    FIRST="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-i|--increment)
	    INCREMENT="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-l|--last)
	    LAST="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-p|--partitions)
	    PARTITIONS="$2"
	    shift # past argument
	    shift # past value
	    ;;	
	-*|--*)
	    echo "Unknown option $1"
	    exit 1
	    ;;
	*)
	    POSITIONAL_ARGS+=("$1") # save positional arg
	    shift # past argument
	    ;;
    esac
done
set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

echo "DATASET    = ${DATASET}"
echo "TOLERANCE  = ${TOLERANCE}"

if [ -z ${PARTITIONS+x} ] # if PARTITIONS does not exist...
then 
    PS=(`seq $FIRST $INCREMENT $LAST`)
    echo "FIRST      = ${FIRST}"
    echo "INCREMENT  = ${INCREMENT}"
    echo "LAST       = ${LAST}"    
else 
    PS=(`seq $PARTITIONS 1 $PARTITIONS`)    
    echo "PARTITIONS = ${PARTITIONS}"
fi

for i in "${PS[@]}"
do
    echo "./QuadPlusPart $i $DATASET $TOLERANCE"
    ./QuadPlusPart $i $DATASET $TOLERANCE
done
