#!/bin/bash

JAR="$HOME/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/geospark-1.2.0.jar:${LIBSPATH}/scallop_2.11-3.1.5.jar:${LIBSPATH}/scala-library-2.11.12.jar:${LIBSPATH}/jgrapht-core-1.4.0.jar"
CLASS="sdcel.bo.RangeTester"

THE_PATH="/home/and/RIDIR/Code/R/biased/"
AS=("0.5K" "1K" "1.5K" "2K" "2K"   "2K" "2K"  "2K")
BS=("2K"   "2K" "2K"   "2K" "2.5K" "3K" "3.5" "4K")

for N in {1..3}; do
    for i in ${!BS[@]}; do
	echo "scala -cp $LIBS:$JAR $CLASS --input1 ${THE_PATH}A$i.wkt --input2 ${THE_PATH}B$i.wkt --tag1 ${AS[$i]} --tag2 ${BS[$i]} --appid $N"
	scala -cp $LIBS:$JAR $CLASS --input1 ${THE_PATH}A$i.wkt --input2 ${THE_PATH}B$i.wkt --tag1 ${AS[$i]} --tag2 ${BS[$i]} --appid $N
    done
done
