#!/bin/bash

JAR="$HOME/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/scallop_2.11-3.1.5.jar:${LIBSPATH}/scala-library-2.11.12.jar"
CLASS="sdcel.bo.RangerTester$delayedInit$body"

java -cp $LIBS:$JAR $CLASS 
