#!/bin/bash

for n in $(seq 1 $1)
do
    for E in 8 4 2 1
    do
	echo "./sdcel_speedup gadm/edges_P8K /home/acald013/Test/edges_P8K 1e8 $E"
	./sdcel_speedup gadm/edges_P8K /home/acald013/Test/edges_P8K 1e8 $E
    done
done
