#!/bin/bash
ES=(3 6 9 12)
FS=("4" "4,3" "4,3,2" "4,3,2,1")
for n in $(seq 1 $1)
do
    for i in 0 1 2 3
    do
	echo "./sdcel_scaleup gadm/edges_P8K /home/acald013/Test/edges_P8K 1e8 ${ES[$i]} ${FS[$i]}"
	./sdcel_scaleup gadm/edges_P8K /home/acald013/Test/edges_P8K 1e8 ${ES[$i]} ${FS[$i]}
    done
done
