#!/bin/bash

PS=(10000 11000 12000 13000 14000 15000)

for n in $(seq 1 $1)
do
    for P in "${PS[@]}"
    do
	echo "
	bash bash/sdcel_partitioner_spark --input1 Census/MainUS/A.wkt --input2 Census/MainUS/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn"
	bash bash/sdcel_partitioner_spark --input1 Census/MainUS/A.wkt --input2 Census/MainUS/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn
    done
done
