#!/bin/bash

LOCAL_PATH=$1
SCALE=$2

SPARK_JARS=$HOME/Spark/2.4/jars/
JAR=$HOME/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar
CLASS="edu.ucr.dblab.sdcel.SDCEL_Local"
LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
MASTER=local[1]

spark-submit \
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars ${SPARK_JARS}geospark-1.2.0.jar,${SPARK_JARS}scallop_2.11-3.1.5.jar,${SPARK_JARS}spark-measure_2.11-0.16.jar \
    --master $MASTER --deploy-mode client \
    --class $CLASS $JAR \
    --input1 file://${LOCAL_PATH}/A.wkt \
    --input2 file://${LOCAL_PATH}/B.wkt \
    --quadtree $LOCAL_PATH/quadtree.wkt \
    --boundary $LOCAL_PATH/boundary.wkt \
    --scale $SCALE --debug
