#!/bin/bash

MASTER=yarn

INPUT1=$1
INPUT2=$2
HDFS_PATH=$3
QUADTREE_PATH=$4
BOUNDARY_PATH=$5
TOLERANCE=$6

echo "rm -f -r ${HDFS_PATH}/edgesA/"
rm -f -r ${HDFS_PATH}/edgesA/
echo "rm -f -r ${HDFS_PATH}/edgesB/"
rm -f -r ${HDFS_PATH}/edgesB/

EXECUTORS=12
CORES=9
DMEMORY=12g
EMEMORY=30g
SPARK_JARS=$HOME/Spark/2.4/jars/
JAR=$HOME/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar
CLASS="edu.ucr.dblab.sdcel.DCELPartitionerByQuadtree"
LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties

spark-submit \
    --master $MASTER \
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --conf spark.driver.maxResultSize=2G \
    --jars ${SPARK_JARS}geospark-1.2.0.jar,${SPARK_JARS}scallop_2.11-3.1.5.jar \
    --master $MASTER --deploy-mode client \
    --num-executors $EXECUTORS --executor-cores $CORES --executor-memory $EMEMORY --driver-memory $DMEMORY \
    --class $CLASS $JAR \
    --input1 $INPUT1 \
    --input2 $INPUT2 \
    --quadtree $QUADTREE_PATH --boundary $BOUNDARY_PATH \
    --apath $HDFS_PATH/edgesA \
    --bpath $HDFS_PATH/edgesB \
    --tolerance $TOLERANCE 
#--debug --readid
