#!/bin/bash

PS=(250 500 750 1000 1500 2000 4000 6000)

for n in $(seq 1 $1)
do
    for P in "${PS[@]}"
    do
	echo "
	bash bash/sdcel_partitioner_spark --input1 extension/CA/A.wkt --input2 extension/CA/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn"
	bash bash/sdcel_partitioner_spark --input1 extension/CA/A.wkt --input2 extension/CA/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn
    done
done
