#!/bin/bash

PS=(1000 2000 3000 4000 5000 6000 7000 8000 9000)

for n in $(seq 1 $1)
do
    for P in "${PS[@]}"
    do
	echo "
	bash bash/sdcel_partitioner_spark --input1 Census/MainUS/A.wkt --input2 Census/MainUS/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn"
	bash bash/sdcel_partitioner_spark --input1 Census/MainUS/A.wkt --input2 Census/MainUS/B.wkt --partitions $P --kpath /tmp/edgesCells_CA_K_${P}.wkt --qpath /tmp/edgesCells_CA_Q_${P}.wkt --master yarn
    done
done
