#!/usr/bin/env bash

CLASS=$1
ARGS=$2

EXECUTORS=12
CORES=9
DMEMORY=30g
EMEMORY=32g
SPARK_JARS=${HOME}/Spark/2.4/jars/
JAR=${HOME}/RIDIR/Code/SDCEL/target/scala-2.11/sdcel_2.11-0.1.jar
LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
MASTER=local[10]
PARAMS=(
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars ${SPARK_JARS}geospark-1.2.0.jar,${SPARK_JARS}scallop_2.11-3.1.5.jar \
    --master $MASTER --deploy-mode client \
    --num-executors $EXECUTORS --executor-cores $CORES --executor-memory $EMEMORY --driver-memory $DMEMORY \
    --class $CLASS $JAR $ARGS
)
echo "spark-submit ${PARAMS[@]}"
spark-submit ${PARAMS[@]}
