#!/bin/bash

for n in $(seq 1 $1)
do
    ./sdcel3 --input1 /home/acald013/Datasets/CA/S/A1_prime.wkt --input2 /home/acald013/Datasets/CA/S/B1_prime.wkt --grids /home/acald013/Datasets/CA/S/K1.wkt --master local[2] --qtag 1
    ./sdcel3 --input1 /home/acald013/Datasets/CA/S/A2_prime.wkt --input2 /home/acald013/Datasets/CA/S/B2_prime.wkt --grids /home/acald013/Datasets/CA/S/K2.wkt --master local[4] --qtag 2	
    ./sdcel3 --input1 /home/acald013/Datasets/CA/S/A4_prime.wkt --input2 /home/acald013/Datasets/CA/S/B4_prime.wkt --grids /home/acald013/Datasets/CA/S/K4.wkt --master local[8] --qtag 4
done
