#!/bin/bash

SPARK_JARS=$HOME/Spark/2.4/jars/
JAR=$HOME/RIDIR/Meetings/next/figures/CC/concurrencycheccker/target/scala-2.11/sdcel_2.11-0.1.jar
CLASS="Main"
LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
MASTER=local[7]

spark-submit \
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars ${SPARK_JARS}scallop_2.11-3.1.5.jar \
    --master $MASTER --deploy-mode client \
    --class $CLASS $JAR $1 \

