#!/bin/bash

JAR="$HOME/RIDIR/Code/Scala/PrecisionChecker/target/scala-2.11/precisionchecker_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/geospark-1.2.0.jar"
CLASS="PointLocator2"

scala -cp $LIBS:$JAR $CLASS 
